[package]
name = "valkey-commands"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
valkey-proto = { path = "../proto" }
valkey-storage = { path = "../storage" }
dashmap = { workspace = true }
fastrand = "2"
rand = "0.8"

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
