[package]
name = "valkey-commands"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
valkey-proto = { path = "../proto" }
valkey-storage = { path = "../storage" }
valkey-pubsub = { path = "../pubsub" }
valkey-persistence = { path = "../persistence" }
valkey-scripting = { path = "../scripting" }
valkey-modules = { path = "../modules" }
valkey-replication = { path = "../replication" }
dashmap = { workspace = true }
fastrand = "2"
rand = "0.8"
ordered-float = { workspace = true }
lazy_static = "1"

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
