[package]
name = "valkey-scripting"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
sha1 = "0.10"
hex = "0.4"
valkey-proto = { path = "../proto" }
valkey-storage = { path = "../storage" }
dashmap = { workspace = true }
tracing = { workspace = true }
